export type FlagScope = 'GENERAL' | 'BACKEND' | 'WEB' | 'MOBILE';

export interface FeatureFlag {
  key: string;
  enabled: boolean;
  description: string;
  scope: FlagScope;
}

export const FLAG_KEYS = {
  GENERAL_DARK_MODE: 'GENERAL_DARK_MODE',
  GENERAL_NOTIFICATION_CENTER: 'GENERAL_NOTIFICATION_CENTER',
  BACKEND_ADVANCED_SEARCH: 'BACKEND_ADVANCED_SEARCH',
  BACKEND_AI_RECOMMENDATIONS: 'BACKEND_AI_RECOMMENDATIONS',
  WEB_NEW_DASHBOARD: 'WEB_NEW_DASHBOARD',
  WEB_EXPERIMENTAL_CHARTS: 'WEB_EXPERIMENTAL_CHARTS',
  MOBILE_BIOMETRIC_AUTH: 'MOBILE_BIOMETRIC_AUTH',
  MOBILE_OFFLINE_MODE: 'MOBILE_OFFLINE_MODE',
} as const;

export type FlagKey = typeof FLAG_KEYS[keyof typeof FLAG_KEYS];
